from __future__ import annotations

import argparse
import bisect
import copy
import json
import math
from pathlib import Path
from typing import Any


PROJECT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = PROJECT / "Versions" / "3.0" / "config.js"
DEFAULT_TARGET = PROJECT / "Versions" / "4.0" / "config.js"

PRIMARY_BG = ("bg_1", "bg_2", "bg_3")
PRIMARY_FG = ("fg_1", "fg_2", "fg_3")
ALIASES = {
    "bg_high": "bg_1",
    "bg_low": "bg_2",
    "fg_high_a": "fg_1",
    "fg_high_j": "fg_1",
    "fg_low": "fg_1",
    "fg_high_k": "fg_2",
    "fg_high_q": "fg_3",
    "super": "sf_1",
}


def load_config(path: Path) -> dict[str, Any]:
    raw = path.read_text(encoding="utf-8-sig")
    start, end = raw.find("{"), raw.rfind("}")
    if start < 0 or end <= start:
        raise ValueError(f"Config JSON not found: {path}")
    config = json.loads(raw[start : end + 1])
    if config.get("game_id") != "H016":
        raise ValueError(f"Not an H016 config: {path}")
    return config


def save_config(path: Path, config: dict[str, Any]) -> None:
    payload = json.dumps(config, ensure_ascii=False, separators=(",", ":"))
    path.write_text(
        "// H016 4.0 natural-math candidate; generated by "
        "其他/工具/tune_v4_natural_style.py.\n"
        f"window.H016_CONFIG={payload};\n",
        encoding="utf-8",
    )


def canonical(symbol: int) -> int:
    return symbol - 8 if 11 <= symbol <= 18 else symbol


def stack_stop_flags(reel: list[int], size: int = 4) -> list[bool]:
    length = len(reel)
    flags: list[bool] = []
    for stop in range(length):
        visible = [canonical(int(reel[(stop + offset) % length])) for offset in range(size)]
        flags.append(
            any(
                visible[index] == visible[index + 1]
                and 3 <= visible[index] <= 10
                for index in range(size - 1)
            )
        )
    return flags


def largest_remainder(values: list[float], total: int, positive_mask: list[bool]) -> list[int]:
    if len(values) != len(positive_mask):
        raise ValueError("values/mask length mismatch")
    result = [0] * len(values)
    active = [index for index, enabled in enumerate(positive_mask) if enabled]
    if not active:
        raise ValueError("No active weights")
    scale = total / sum(values[index] for index in active)
    exact = [values[index] * scale for index in active]
    floors = [max(1, math.floor(value)) for value in exact]
    for index, value in zip(active, floors):
        result[index] = value
    remainder = total - sum(result)
    if remainder > 0:
        order = sorted(
            range(len(active)),
            key=lambda offset: (exact[offset] - floors[offset], -active[offset]),
            reverse=True,
        )
        for offset in order[:remainder]:
            result[active[offset]] += 1
    elif remainder < 0:
        order = sorted(
            range(len(active)),
            key=lambda offset: (exact[offset] - floors[offset], active[offset]),
        )
        needed = -remainder
        for offset in order:
            index = active[offset]
            removable = min(needed, result[index] - 1)
            result[index] -= removable
            needed -= removable
            if needed == 0:
                break
        if needed:
            raise ValueError("Could not preserve positive integer weights")
    if sum(result) != total:
        raise AssertionError("Largest-remainder total mismatch")
    return result


def suppress_stack_weights(table: dict[str, Any], scale: float) -> dict[str, Any]:
    audit = {"before": [], "after": []}
    for reel_index, (reel, weights) in enumerate(zip(table["reels"], table["weights"])):
        flags = stack_stop_flags(list(map(int, reel)))
        original = list(map(int, weights))
        total = sum(original)
        if total <= 0:
            raise ValueError(f"R{reel_index + 1}: non-positive stop total")
        audit["before"].append(sum(w for w, flag in zip(original, flags) if flag) / total)
        adjusted = [
            (weight / scale if flag else float(weight))
            for weight, flag in zip(original, flags)
        ]
        table["weights"][reel_index] = largest_remainder(
            adjusted, total, [weight > 0 for weight in original]
        )
        updated = table["weights"][reel_index]
        audit["after"].append(sum(w for w, flag in zip(updated, flags) if flag) / sum(updated))
    return audit


def position_exposure(weights: list[int], position: int, size: int = 4) -> int:
    length = len(weights)
    return sum(int(weights[(position - offset) % length]) for offset in range(size))


def nearest_half_subset(contributions: list[int]) -> set[int]:
    count = len(contributions)
    if not count:
        return set()
    midpoint = count // 2
    left, right = contributions[:midpoint], contributions[midpoint:]

    def subset_sums(values: list[int]) -> list[tuple[int, int]]:
        result = [(0, 0)]
        for index, value in enumerate(values):
            result += [(total + value, mask | (1 << index)) for total, mask in result]
        return result

    left_sums = subset_sums(left)
    right_sums = sorted(subset_sums(right), key=lambda item: item[0])
    right_totals = [item[0] for item in right_sums]
    target = sum(contributions) / 2.0
    best: tuple[float, int, int] | None = None
    for left_total, left_mask in left_sums:
        offset = bisect.bisect_left(right_totals, target - left_total)
        for candidate in (offset - 1, offset):
            if not 0 <= candidate < len(right_sums):
                continue
            right_total, right_mask = right_sums[candidate]
            difference = abs(left_total + right_total - target)
            trial = (difference, left_mask, right_mask)
            if best is None or trial < best:
                best = trial
    assert best is not None
    _, left_mask, right_mask = best
    selected = {index for index in range(len(left)) if left_mask & (1 << index)}
    selected.update(
        midpoint + index for index in range(len(right)) if right_mask & (1 << index)
    )
    return selected


def halve_initial_gold(table: dict[str, Any]) -> list[dict[str, Any]]:
    audits: list[dict[str, Any]] = []
    for reel_index, (reel, weights) in enumerate(zip(table["reels"], table["weights"])):
        for base_symbol in range(3, 11):
            gold_symbol = base_symbol + 8
            positions = [index for index, symbol in enumerate(reel) if int(symbol) == gold_symbol]
            if not positions:
                continue
            contributions = [position_exposure(weights, position) for position in positions]
            selected_offsets = nearest_half_subset(contributions)
            kept = 0
            original = sum(contributions)
            for offset, position in enumerate(positions):
                if offset in selected_offsets:
                    kept += contributions[offset]
                else:
                    reel[position] = base_symbol
            audits.append(
                {
                    "reel": reel_index + 1,
                    "symbol": base_symbol,
                    "gold_positions_before": len(positions),
                    "gold_positions_after": len(selected_offsets),
                    "weighted_ratio_to_fg1": kept / original if original else 0.0,
                }
            )
    return audits


def halve_drop_gold(table: dict[str, Any]) -> list[dict[str, float]]:
    audits: list[dict[str, float]] = []
    for reel_index, (values, weights) in enumerate(zip(table["drop_values"], table["drop_weights"])):
        values = list(map(int, values))
        original = list(map(int, weights))
        total = sum(original)
        gold = sum(weight for symbol, weight in zip(values, original) if 11 <= symbol <= 18)
        base = total - gold
        if gold <= 0 or base <= 0:
            audits.append({"reel": reel_index + 1, "before": gold / total if total else 0.0, "after": 0.0})
            continue
        factor = base / (2 * base + gold)
        adjusted = [
            weight * factor if 11 <= symbol <= 18 else float(weight)
            for symbol, weight in zip(values, original)
        ]
        updated = largest_remainder(adjusted, total, [weight > 0 for weight in original])
        table["drop_weights"][reel_index] = updated
        new_gold = sum(weight for symbol, weight in zip(values, updated) if 11 <= symbol <= 18)
        audits.append({"reel": reel_index + 1, "before": gold / total, "after": new_gold / total})
    return audits


def random_wild(weights: list[int], zero_weight: int) -> list[int]:
    if len(weights) != 4:
        raise ValueError("Random Wild must have four weights")
    return [int(zero_weight), int(weights[1]), int(weights[2]), int(weights[3])]


def main() -> None:
    parser = argparse.ArgumentParser(description="Tune H016 4.0 BG/FG natural style")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--target", type=Path, default=DEFAULT_TARGET)
    parser.add_argument("--stack-scale", type=float, default=1.2)
    parser.add_argument("--bg1-zero", type=int, default=21860)
    parser.add_argument("--bg2-zero", type=int, default=12792)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.stack_scale < 1:
        raise ValueError("stack-scale must be >= 1")

    baseline = load_config(args.source)
    target = load_config(args.target)
    if str(target.get("excel_version")) != "4":
        raise ValueError("Target must be the H016 4.0 candidate")

    for table_name in (*PRIMARY_BG, *PRIMARY_FG):
        target["tables"][table_name] = copy.deepcopy(baseline["tables"][table_name])
    # BF is an independent, entry-only board.  This BG/FG tuning must not
    # replace it with bg_3.  Version 4 keeps the version-3 BF board unchanged.
    target["tables"]["buy"] = copy.deepcopy(baseline["tables"]["buy"])

    stack_audit: dict[str, Any] = {}
    for table_name in (*PRIMARY_BG, *PRIMARY_FG):
        stack_audit[table_name] = suppress_stack_weights(
            target["tables"][table_name], args.stack_scale
        )

    target["tables"]["bg_1"]["random_wild"]["weights"] = random_wild(
        target["tables"]["bg_1"]["random_wild"]["weights"], args.bg1_zero
    )
    target["tables"]["bg_2"]["random_wild"]["weights"] = random_wild(
        target["tables"]["bg_2"]["random_wild"]["weights"], args.bg2_zero
    )
    target["tables"]["bg_3"]["random_wild"]["weights"] = [1, 0, 0, 0]

    # FG3 is the normal FG table with half the initial/drop gold exposure.
    target["tables"]["fg_3"] = copy.deepcopy(target["tables"]["fg_1"])
    target["tables"]["fg_3"]["random_wild"] = copy.deepcopy(
        baseline["tables"]["fg_3"]["random_wild"]
    )
    initial_gold_audit = halve_initial_gold(target["tables"]["fg_3"])
    drop_gold_audit = halve_drop_gold(target["tables"]["fg_3"])

    for selection_name in ("free", "retrigger"):
        target["table_selection"][selection_name] = [
            {"table": "fg_1", "weight": 4000},
            {"table": "fg_2", "weight": 3000},
            {"table": "fg_3", "weight": 3000},
        ]

    for alias, primary in ALIASES.items():
        target["tables"][alias] = copy.deepcopy(target["tables"][primary])

    all_primary = (*PRIMARY_BG, *PRIMARY_FG)
    validation = {
        "reel_lengths_200": all(
            len(reel) == 200
            for name in all_primary
            for reel in target["tables"][name]["reels"]
        ),
        "weight_lengths_200": all(
            len(weights) == 200
            for name in all_primary
            for weights in target["tables"][name]["weights"]
        ),
        "integer_weights": all(
            isinstance(weight, int) and weight >= 0
            for name in all_primary
            for weights in target["tables"][name]["weights"]
            for weight in weights
        ),
        "selection_free": target["table_selection"]["free"],
        "selection_retrigger": target["table_selection"]["retrigger"],
        "aliases_match": all(target["tables"][alias] == target["tables"][primary] for alias, primary in ALIASES.items()),
    }
    if not all(value is True for key, value in validation.items() if isinstance(value, bool)):
        raise AssertionError(validation)

    if args.write:
        save_config(args.target, target)

    random_audit = {}
    for name in PRIMARY_BG:
        weights = target["tables"][name]["random_wild"]["weights"]
        random_audit[name] = {
            "weights": weights,
            "nonzero_draw_rate": sum(weights[1:]) / sum(weights),
        }
    print(
        json.dumps(
            {
                "source": str(args.source.resolve()),
                "target": str(args.target.resolve()),
                "written": args.write,
                "stack_scale": args.stack_scale,
                "stack_rng_rate": stack_audit,
                "bg_random_wild": random_audit,
                "fg3_initial_gold": initial_gold_audit,
                "fg3_drop_gold": drop_gold_audit,
                "validation": validation,
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
