from __future__ import annotations

import argparse
import copy
import importlib.util
import json
import os
import sys
from pathlib import Path
from typing import Any


PROJECT = Path(__file__).resolve().parents[2]
V4_BASE = PROJECT / "Versions" / "4.0" / "config.js"
V4_RTP_92 = PROJECT / "Versions" / "4.0" / "config_92A.js"
V4_RTP_94 = PROJECT / "Versions" / "4.0" / "config_94A.js"
SIMULATOR = PROJECT / "Simulator.py"


def load_config(path: Path) -> dict[str, Any]:
    raw = path.read_text(encoding="utf-8-sig")
    start, end = raw.find("{"), raw.rfind("}")
    if start < 0 or end <= start:
        raise ValueError(f"Config JSON not found: {path}")
    return json.loads(raw[start : end + 1])


def load_module():
    os.environ["H016_CONFIG_FILE"] = "Versions/4.0/config.js"
    os.environ["H016_CONFIG_RTP_FILE"] = "Versions/4.0/config_92A.js"
    os.environ["H016_CARD_SYSTEM_ENABLED"] = "true"
    os.environ["H016_CARD_SYSTEM_IS_NEWBIE"] = "false"
    os.environ["H016_RUN_ALL_COMBINATIONS"] = "false"
    os.environ["H016_OUTPUT_REPORT"] = "false"
    name = "h016_v5_tuner_simulator"
    spec = importlib.util.spec_from_file_location(name, SIMULATOR)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot import {SIMULATOR}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def weight_tools():
    tool_path = Path(__file__).with_name("tune_v4_natural_style.py")
    name = "h016_v4_weight_tools"
    spec = importlib.util.spec_from_file_location(name, tool_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot import {tool_path}")
    tool = importlib.util.module_from_spec(spec)
    sys.modules[name] = tool
    spec.loader.exec_module(tool)
    return tool


def suppress_stack_weights(module, table: dict[str, Any], scale: float) -> None:
    weight_tools().suppress_stack_weights(table, scale)


def capped_stack_weights(table: dict[str, Any], ratio: float) -> None:
    tool = weight_tools()
    for reel_index, (reel, weights) in enumerate(zip(table["reels"], table["weights"])):
        flags = tool.stack_stop_flags(list(map(int, reel)))
        original = list(map(int, weights))
        values = [1.0 if flag else float(ratio) for flag in flags]
        table["weights"][reel_index] = tool.largest_remainder(
            values,
            sum(original),
            [weight > 0 for weight in original],
        )


def adjust_natural_candidate(
    config: dict[str, Any],
    module,
    scale2: float,
    scale3: float,
    fg2_share: float,
    capped: bool = False,
) -> dict[str, Any]:
    adjust = capped_stack_weights if capped else lambda table, value: suppress_stack_weights(module, table, value)
    adjust(config["tables"]["fg_2"], scale2)
    adjust(config["tables"]["fg_3"], scale3)
    # Keep the v4/competitor 2:3:4 conditional distribution.  fg_3 used to
    # disable the feature entirely; v5 gives it the same distribution as fg_2.
    config["tables"]["fg_3"]["random_wild"] = copy.deepcopy(
        config["tables"]["fg_2"]["random_wild"]
    )
    weight2 = int(round(fg2_share * 10_000))
    rows = [
        {"table": "fg_1", "weight": 0},
        {"table": "fg_2", "weight": weight2},
        {"table": "fg_3", "weight": 10_000 - weight2},
    ]
    config["table_selection"]["free"] = copy.deepcopy(rows)
    config["table_selection"]["retrigger"] = copy.deepcopy(rows)
    config["tables"]["fg_high_k"] = copy.deepcopy(config["tables"]["fg_2"])
    config["tables"]["fg_high_q"] = copy.deepcopy(config["tables"]["fg_3"])
    return config


def make_natural_candidate(
    module,
    scale2: float,
    scale3: float,
    fg2_share: float,
    capped: bool = False,
) -> dict[str, Any]:
    config = load_config(V4_BASE)
    return adjust_natural_candidate(config, module, scale2, scale3, fg2_share, capped)


def make_candidate(
    module,
    scale2: float,
    scale3: float,
    fg2_share: float,
    capped: bool = False,
) -> dict[str, Any]:
    natural = make_natural_candidate(module, scale2, scale3, fg2_share, capped)
    return module.compose_runtime_config(natural, load_config(V4_RTP_92))


def save_js(path: Path, variable: str, config: dict[str, Any], note: str) -> None:
    payload = json.dumps(config, ensure_ascii=False, separators=(",", ":"))
    path.write_text(f"// {note}\nwindow.{variable}={payload};\n", encoding="utf-8")


def write_v5(module, scale2: float, scale3: float, fg2_share: float, capped: bool) -> None:
    natural = make_natural_candidate(module, scale2, scale3, fg2_share, capped)
    natural["excel_version"] = "5"
    save_js(
        PROJECT / "config.js",
        "H016_CONFIG",
        natural,
        "H016 v5 natural math; generated by 其他/工具/tune_v5_fg.py.",
    )
    for source, target, variable in (
        (V4_RTP_92, PROJECT / "config_92A.js", "H016_CONFIG"),
        (V4_RTP_94, PROJECT / "config_94A.js", "H016_CONFIG"),
    ):
        previous = load_config(source)
        config = module.compose_runtime_config(natural, previous)
        config["excel_version"] = "5.0.0.0"
        config["runtime_version"] = "5.0.0.0"
        save_js(
            target,
            variable,
            config,
            "H016 v5 RTP/Card config; v4 multiplier weights preserved.",
        )


def run(module, config: dict[str, Any], rounds: int, card_on: bool, seed: int) -> dict[str, Any]:
    module.CARD_SYSTEM_ENABLED = bool(card_on)
    module.CARD_SYSTEM_IS_NEWBIE = False
    return module.run_simulation(
        total_rounds=rounds,
        bet_mode=0,
        bet_multi=1,
        threads=8,
        config=config,
        seed=seed,
    )


def metrics(module, off: dict[str, Any], on: dict[str, Any]) -> dict[str, float]:
    off_stats, on_stats = off["stats"], on["stats"]
    tail_index = module.MULTIPLIER_THRESHOLDS.index(2000)
    sessions = max(1, int(off_stats["fg_triggers"]))
    fg_spins = max(1, int(on_stats["fg_spins"]))
    events = int(off_stats["fg_w2_events"])
    counts = [int(off_stats["fg_w2_counts"][value]) for value in (2, 3, 4)]
    total_counts = max(1, sum(counts))
    coin_in = max(1.0, float(on_stats["coin_in"]))
    return {
        "hit_on_pct": 100.0 * float(on_stats["fg_hit_spins"]) / fg_spins,
        "tail_off_pct": 100.0 * float(off_stats["multiplier_fg_count"][tail_index]) / sessions,
        "tail_count": float(off_stats["multiplier_fg_count"][tail_index]),
        "sessions": float(sessions),
        "w2_cycle": float(off_stats["fg_spins"]) / events if events else float("inf"),
        "w2_2_pct": 100.0 * counts[0] / total_counts,
        "w2_3_pct": 100.0 * counts[1] / total_counts,
        "w2_4_pct": 100.0 * counts[2] / total_counts,
        "rtp_on_pct": 100.0 * (float(on_stats["pay_bg"]) + float(on_stats["pay_fg"])) / coin_in,
        "retry_avg": float(on_stats.get("retry_total", 0)) / max(1, int(on_stats["rounds"])),
        "retry_failed": float(on_stats.get("retry_limit_exceeded", 0)),
    }


def score(row: dict[str, float]) -> float:
    penalty = abs(row["hit_on_pct"] - 40.5)
    if row["hit_on_pct"] < 40.0:
        penalty += (40.0 - row["hit_on_pct"]) * 8.0
    if row["tail_off_pct"] < 0.1:
        penalty += (0.1 - row["tail_off_pct"]) * 200.0
    if row["w2_cycle"] > 47.46:
        penalty += (row["w2_cycle"] - 47.46) * 2.0
    return penalty


def main() -> None:
    parser = argparse.ArgumentParser(description="Search H016 v5 FG natural parameters.")
    parser.add_argument("--off-rounds", type=int, default=1_500_000)
    parser.add_argument("--on-rounds", type=int, default=150_000)
    parser.add_argument("--top", type=int, default=8)
    parser.add_argument("--scale2", type=float)
    parser.add_argument("--scale3", type=float)
    parser.add_argument("--fg2-share", type=float)
    parser.add_argument("--extended", action="store_true")
    parser.add_argument("--capped", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    module = load_module()
    if args.scale2 is not None or args.scale3 is not None or args.fg2_share is not None:
        if args.scale2 is None or args.scale3 is None or args.fg2_share is None:
            parser.error("--scale2, --scale3 and --fg2-share must be supplied together")
        candidate = make_candidate(module, args.scale2, args.scale3, args.fg2_share, args.capped)
        off = run(module, candidate, args.off_rounds, False, 5_100_000)
        on = run(module, candidate, args.on_rounds, True, 5_200_000)
        row = {
            "scale2": args.scale2,
            "scale3": args.scale3,
            "fg2_share": args.fg2_share,
            **metrics(module, off, on),
        }
        row["score"] = score(row)
        print(json.dumps(row, ensure_ascii=False, indent=2))
        if args.write:
            write_v5(module, args.scale2, args.scale3, args.fg2_share, args.capped)
            print("written=v5")
        return
    if args.write:
        parser.error("--write requires --scale2, --scale3 and --fg2-share")
    rows: list[dict[str, float]] = []
    if args.capped:
        scale2_values = (6.0, 9.0, 12.0)
        scale3_values = (6.0, 9.0, 12.0)
        share2_values = (0.55, 0.65, 0.75)
    elif args.extended:
        scale2_values = (12.0, 16.0, 20.0)
        scale3_values = (8.0, 10.0, 12.0)
        share2_values = (0.60, 0.65, 0.70, 0.75)
    else:
        scale2_values = (8.0, 10.0, 12.0)
        scale3_values = (6.0, 8.0, 10.0)
        share2_values = (0.35, 0.45, 0.55)
    for scale2 in scale2_values:
        for scale3 in scale3_values:
            for share2 in share2_values:
                candidate = make_candidate(module, scale2, scale3, share2, args.capped)
                off = run(module, candidate, args.off_rounds, False, 5_100_000)
                on = run(module, candidate, args.on_rounds, True, 5_200_000)
                row = {
                    "scale2": scale2,
                    "scale3": scale3,
                    "fg2_share": share2,
                    **metrics(module, off, on),
                }
                row["score"] = score(row)
                rows.append(row)
    rows.sort(key=lambda row: row["score"])
    keys = (
        "scale2", "scale3", "fg2_share", "hit_on_pct", "tail_off_pct",
        "tail_count", "sessions", "w2_cycle", "w2_2_pct", "w2_3_pct",
        "w2_4_pct", "rtp_on_pct", "retry_avg", "retry_failed", "score",
    )
    print("\t".join(keys))
    for row in rows[: max(1, args.top)]:
        print("\t".join(f"{row[key]:.6f}" for key in keys))


if __name__ == "__main__":
    main()
